# Generated by Django 4.0.3 on 2022-03-24 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_client_inventory_visit_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
