# Generated by Django 4.0.3 on 2022-03-25 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_order_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
